// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGNQXe_3qvf-g9rJK5rnUNyR6z_5yoV6s',
    appId: '1:414246258271:web:2b49045afbfdb41fb6bdea',
    messagingSenderId: '414246258271',
    projectId: 'fhainspectorapp-61618',
    authDomain: 'fhainspectorapp-61618.firebaseapp.com',
    storageBucket: 'fhainspectorapp-61618.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw5E1iomb6w5rdhm_UQ6sduzAIchRwlcw',
    appId: '1:414246258271:android:de7f4893562b84b7b6bdea',
    messagingSenderId: '414246258271',
    projectId: 'fhainspectorapp-61618',
    storageBucket: 'fhainspectorapp-61618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh8VtDeLDV8NxTsOL84qrB2EoaJSqpkkw',
    appId: '1:414246258271:ios:576cd6379cb1f20bb6bdea',
    messagingSenderId: '414246258271',
    projectId: 'fhainspectorapp-61618',
    storageBucket: 'fhainspectorapp-61618.firebasestorage.app',
    iosBundleId: 'com.fhainspector.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh8VtDeLDV8NxTsOL84qrB2EoaJSqpkkw',
    appId: '1:414246258271:ios:b89e880bcfd59458b6bdea',
    messagingSenderId: '414246258271',
    projectId: 'fhainspectorapp-61618',
    storageBucket: 'fhainspectorapp-61618.firebasestorage.app',
    iosBundleId: 'com.example.artneidichApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGNQXe_3qvf-g9rJK5rnUNyR6z_5yoV6s',
    appId: '1:414246258271:web:6a8aecf030b8f6e3b6bdea',
    messagingSenderId: '414246258271',
    projectId: 'fhainspectorapp-61618',
    authDomain: 'fhainspectorapp-61618.firebaseapp.com',
    storageBucket: 'fhainspectorapp-61618.firebasestorage.app',
  );
}
